void interrupt_init();
void handler_reset();
void handler_undefined();
void handler_svc();
void handler_prefetchabort();
void handler_dataabort();
void handler_reserved();
void handler_irq();
void handler_fiq();